version: "3.8"

services:
  webhaproxy:
    image: nginx:latest
    volumes:
      - ../sources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - backendapi

  api:
    image: 127.0.0.1:5000/appapi:1
    build: ../sources/webapp/Dockerfile
    ports:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://test:123abcD@database:5432/mydb
    volumes:
      - applogs:/var/logs
    depends_on:
      - database
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - backendapi
      - appdatabase

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123abcD
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appdatabase

volumes:
  applogs:
  pgdata:

networks:
  backendapi:
  appdatabase:
