apiVersion: v1
kind: Pod
metadata:
  namespace: test2 # hidden value namespace: default
  name: helloworld
spec:
  containers:
    - image: nginx:latest
      name: my-alpin #unique name
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: 512Mi
          cpu: 256m
        requests:
          memory: 512Mi
          cpu: 256m
      env:
        - name: HELLO
          value: '{ "key": "value"}'
