apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: nginx
  name: nginxxxx
  labels:
    app: nginx_daemonset
spec:
  selector:
    matchLabels:
      app: nginx_daemonset
  template:
    metadata:
      labels:
        app: nginx_daemonset
    spec:
      containers:
        - image: nginx:1.29.0-alpine
          name: app-1
          resources:
            limits:
              memory: 512Mi
              cpu: 256m
            requests:
              memory: 512Mi
              cpu: 256m
          env:
            - name: HELLO2
              value: "HOW ARE YOU"
