apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx-deployment
  labels:
    app: nginx_haproxy
    important: "true"
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx_haproxy
  template:
    metadata:
      labels:
        app: nginx_haproxy
    spec:
      containers:
        - image: nginx:1.29.0-alpine
          name: app-1
          resources:
            limits:
              memory: 56Mi
              cpu: 25m
            requests:
              memory: 56Mi
              cpu: 25m
          env:
            - name: HELLO2
              value: "HOW ARE YOU"
