apiVersion: v1
kind: Pod
metadata:
  namespace: nginx # hidden value namespace: default
  name: helloworld
spec:
  containers:
    - name: nginx
      image: "nginx"
      resources:
        requests:
          cpu: 512m
          memory: 512Mi
        limits:
          cpu: 512m
          memory: 512Mi
      env:
        - name: MESSAGE
          value: "hello world"
  restartPolicy: Never
