---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-crds-access
rules:
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - globalnetworkpolicies
      - globalnetworksets
      - networkpolicies
      - hostendpoints
      - clusterinformations
      - ippools
      - felixconfigurations
      - bgppeers
      - bgpconfigurations
      - ipamblocks
      - ipamconfigs
      - ipamhandles
      - blockaffinities
      - nodes
      - tiers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-crds-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-crds-access
subjects:
  - kind: ServiceAccount
    name: calico-node
    namespace: kube-system
