apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx-haproxy
  labels:
    app: nginx-haproxy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-haproxy
  template:
    metadata:
      labels:
        app: nginx-haproxy
    spec:
      affinity:
        nodeAffinity:
          # hard rule
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - ap-southeast-1b
                      - ap-southeast-1c
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ip-10-0-31-63.ap-southeast-1.compute.internal
                      - ip-10-0-36-73.ap-southeast-1.compute.internal

          #soft rule
          # preferredDuringSchedulingIgnoredDuringExecution:
          #   - weight: 80
          #     preference:
          #       matchExpressions:
          #         - key: topology.kubernetes.io/zone
          #           operator: In
          #           values:
          #             - ap-southeast-1d
          #   - weight: 20
          #     preference:
          #       matchExpressions:
          #         - key: topology.kubernetes.io/zone
          #           operator: In
          #           values:
          #             - ap-southeast-1b
      containers:
        - name: random
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: 256m
            requests:
              memory: 512Mi
              cpu: 256m
          env:
            - name: HELLO
              value: "HOW ARE YOU"
