# 1. ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exec-access-sa
  namespace: default

---
# 2. Role granting exec permission
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
# 3. RoleBinding to bind Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: exec-access-sa
    namespace: default
roleRef:
  kind: Role
  name: exec-role
  apiGroup: rbac.authorization.k8s.io
