# Pod using the PVC
apiVersion: v1
kind: Pod
metadata:
  # namespace: test
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      resources:
        requests:
          cpu: 256m
          memory: 512Mi
        limits:
          cpu: 256m
          memory: 512Mi
      volumeMounts:
        - mountPath: "/datatest"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc-rox
