apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test
  name: pvc-rox
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: pv-rox-practices
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test
  name: pvc-rox-2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: pvc-rox
